apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: neo4jdb
  labels:
    app: neo4jdb
spec:
  serviceName: neo4jsvc
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4jdb
    spec:
      containers:
      - name: db
        image: neo4j
        env:
        - name: NEO4J_AUTH
          value: none 
        ports:
          - containerPort: 7474
          - containerPort: 7687
        volumeMounts:
          - name: neo4j-data
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 128Gi
