apiVersion: v1
kind: Service
metadata:
  name: neo4jdb-svc
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: web
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4jdb
  type: LoadBalancer